### Get JWT — run this first, token is saved to {{auth_token}}
POST http://localhost:9090/realms/quarkus/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=backend-service&client_secret=secret&username=alice&password=alice&grant_type=password

> {%
  client.global.set("auth_token", response.body.access_token);
%}

###
POST http://localhost:8080/pets
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "petType": "CAT",
  "name": "Whiskers",
  "breedType": "PERSIAN",
  "indoor": true
}

<> 2026-05-03T182913.201.json
<> 2026-05-03T182859.201.json

###
PUT http://localhost:8080/pets/ea8e6ab0-8c2b-4765-a2ba-132412fe39eb
Content-Type: application/json

{
  "petType": "CAT",
  "name": "Whiskers",
  "breedType": "PERSIAN",
  "indoor": true
}
