apiVersion: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040
    isDefault: false
    jsonData:
      minStep: "15s"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    isDefault: true
    jsonData:
      tracesToProfilesV2:
        datasourceUid: pyroscope
        profileTypes:
          - type: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
            label: "CPU"
          - type: "memory:alloc_in_new_tlab_bytes:bytes:space:bytes"
            label: "Alloc"
      tracesToLogs: {}
      serviceMap:
        datasourceUid: "tempo"
      nodeGraph:
        enabled: true
