apiVersion: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    url: http://pyroscope:4040
    isDefault: true
    jsonData:
      minStep: "15s"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://otel-collector:4317
    jsonData:
      tracesToProfiles:
        datasourceUid: pyroscope
        profileTypeId: "process_cpu:wall:nanoseconds:cpu:nanoseconds"
        customQuery: false
